export const CHANFE_PWD = "CHNAGE_PWD"
export const CHANFE_MOBILE_PWD = "CHANFE_MOBILE_PWD"
export const CHANFE_MOBILE = "CHANFE_MOBILE"
export const CHANGE_MINE_INDEX = "CHANGE_MINE_INDEX"
export const CHANGE_MINE_TEL = "CHANGE_MINE_TEL"


// CHANGE_MINE_TEL